### ISSUE TITLE
Error type is private

### ISSUE THREAD

**Issue by mullr** [zeta12ti/parse_duration#15]
The `Error` enum, returned by the `parse` function, is not available outside the crate. This makes it hard to do anything about  `parse`-related error cases.

**Comment by zeta12ti** [comment]
~~It [should be](https://github.com/zeta12ti/parse_duration/blob/master/src/parse.rs#L32) public. Or were you talking about something else?~~

I see the issue. the module `parse` itself is private. That should be an easy fix.

**Comment by zeta12ti** [comment]
Fixed by #16.
